services:
  web:
    container_name: stockcontrol-web
    build: 
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:8080
    depends_on:
      - db
      - api

  api:
    container_name: stockcontrol-api
    build: 
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:admin@db:5432/stock_control
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: stockcontrol-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stock_control
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: